/**
 * Owner/reviewer callback construction for the integrated run (A10-W.8b).
 *
 * One code path, two modes. MOCK writes deterministic content + returns a deterministic
 * review (for tests/CI/demos/offline). REAL reuses the A10-W.7 pilot wiring: the real
 * owner adapter writes inside the worktree and its changes are replayed through the
 * path/role-checked `ctx.write` (so reconcile attributes them), and the real cross-vendor
 * reviewer runs read-only with a strict REVIEW_VERDICT parse. Both modes stream
 * provider-level events to the shared sink; neither can masquerade as the other.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import {
  AgentExecutionRequestSchema,
  type CapabilityBinding,
  type CapabilitySnapshot,
  type ProviderId,
  type ReviewFindings
} from "@triforge/shared";
import { createConfiguredAdapter, type ProviderMode } from "../../providers/configuredAdapter.js";
import type { WritableProfile } from "../../providers/real/index.js";
import { buildReviewFindings, type RawReviewFinding } from "../../orchestration/reviewProtocol.js";
import { computeWorktreeChanges } from "../ledger/index.js";
import type { GitRunner } from "../worktree/index.js";
import type { OwnerContext, OwnerImplement, ReviewContext, ReviewerReview } from "../e2e/writableRun.js";
import type { IntegratedRunSpec } from "./types.js";

export type StageSink = (e: {
  type: string;
  payload: Record<string, unknown>;
  provider?: ProviderId | null;
}) => Promise<void>;

/** Lets the service interrupt an in-flight real provider execution (Job Object kill). */
export interface RunControls {
  /** Register an active execution's cancel thunk; the service calls it on cancel. */
  register(cancel: () => Promise<void>): void;
  /** True once the service has requested cancellation. */
  isCancelRequested(): boolean;
}

export interface RunPlan {
  ownerImplement: OwnerImplement;
  reviewerReview: ReviewerReview;
}

export const INTEGRATED_BINDING: CapabilityBinding = {
  threat: ["T-INT-14", "T-CMP-06"],
  control: ["A10-W.2 path policy", "A10-W.4 Job Object", "A5.5 mutation ledger", "A5.8 governance"],
  milestone: "A10-W.8b",
  verification: ["integratedRun.e2e.test.ts", "windows_integrated_product_e2e"],
  recovery: "revert the worktree branch; the fixture base is disposable",
  residualRisk: "RR-4"
};

/** Deterministic mock owner + reviewer. Real git/ledger/gates/governance; only the
 *  "intelligence" is simulated. The mock NEVER claims to be a real provider. */
function buildMockPlan(spec: IntegratedRunSpec, sink: StageSink, gitRunner: GitRunner): RunPlan {
  const ownerImplement: OwnerImplement = async (ctx: OwnerContext, round: number) => {
    await sink({ type: "agent.message", payload: { text: `mock owner planning (round ${round})` }, provider: spec.owner });
    if (round > 0) {
      return; // converges on the first round
    }
    const dir = spec.writePaths[0] ?? "src";
    const target = `${dir}/triforge_generated.txt`;
    const content = `generated by the mock owner for objective:\n${spec.objective}\n`;
    const res = await ctx.write(target, content, "mock owner implement");
    if (res.ok) {
      await sink({ type: "file.changed", payload: { path: target, bytes: content.length }, provider: spec.owner });
    } else {
      await sink({ type: "warning.raised", payload: { reason: res.reason ?? "write denied", path: target }, provider: spec.owner });
    }
  };

  const reviewerReview: ReviewerReview = async (_ctx: ReviewContext, gatesPassed: boolean): Promise<ReviewFindings> => {
    await sink({
      type: "agent.message",
      payload: { text: `mock reviewer verdict: ${gatesPassed ? "PASS" : "FAIL"}` },
      provider: spec.reviewer
    });
    const raw: RawReviewFinding[] = gatesPassed
      ? [{ severity: "observation", category: "clean_review", evidence: "mock reviewer found no defect and the gates pass", impact: "none observed", requiredAction: "proceed to the governed merge", confidence: 0.7 }]
      : [{ severity: "major", category: "failing_gate", evidence: "the quality gates failed against the owner's changes", impact: "the task is not complete until the gates pass", requiredAction: "repair the implementation", confidence: 0.9 }];
    return buildReviewFindings(spec.reviewer, `mock review by ${spec.reviewer}: ${gatesPassed ? "PASS" : "FAIL"}`, raw);
  };

  return { ownerImplement, reviewerReview };
}

/** Real owner + cross-vendor reviewer (reuses the A10-W.7 pilot semantics). */
function buildRealPlan(
  spec: IntegratedRunSpec,
  sink: StageSink,
  gitRunner: GitRunner,
  ownerSnapshot: CapabilitySnapshot,
  controls: RunControls
): RunPlan {
  const timeoutMs = spec.budget.perRunTimeoutMs;

  const ownerImplement: OwnerImplement = async (ctx: OwnerContext, round: number) => {
    const profile: WritableProfile = {
      observedCapability: ownerSnapshot,
      binding: INTEGRATED_BINDING,
      worktreeRoot: ctx.worktreePath
    };
    const adapter = createConfiguredAdapter(spec.owner, "real", { real: { writableProfile: profile } });
    const ownerExecutionId = `integrated-owner-r${round}`;
    controls.register(() => adapter.cancel(ownerExecutionId));
    const objective =
      round === 0
        ? spec.objective
        : `${spec.objective}\n\nThe quality gates are STILL FAILING. Inspect the failing output and fix the implementation so every gate passes. Change only what is necessary.`;
    const request = AgentExecutionRequestSchema.parse({
      executionId: ownerExecutionId,
      provider: spec.owner,
      objective,
      cwd: ctx.worktreePath,
      readOnly: false,
      timeoutMs,
      ...(spec.ownerModel ? { model: spec.ownerModel } : {})
    });
    for await (const event of adapter.execute(request)) {
      if (event.type === "agent.message") {
        await sink({ type: "agent.message", payload: { text: String((event.payload as { text?: string }).text ?? "") }, provider: spec.owner });
      } else if (event.type === "tool.started" || event.type === "tool.completed") {
        await sink({ type: event.type, payload: { ...(event.payload as Record<string, unknown>) }, provider: spec.owner });
      } else if (event.type === "quota.updated" || event.type === "usage.updated") {
        await sink({ type: event.type, payload: { ...(event.payload as Record<string, unknown>) }, provider: spec.owner });
      }
    }
    // Replay the provider's real writes into the ledger via the path/role-checked write.
    const changes = await computeWorktreeChanges(gitRunner, ctx.worktreePath);
    for (const change of changes) {
      if (change.status === "delete") {
        continue;
      }
      const abs = path.join(ctx.worktreePath, change.relPath);
      let content: string | null = null;
      try {
        content = await fs.readFile(abs, "utf8");
      } catch {
        content = null;
      }
      if (content === null) {
        continue;
      }
      const written = await ctx.write(change.relPath, content, `owner ${spec.owner} edit (round ${round})`);
      await sink({
        type: written.ok ? "file.changed" : "warning.raised",
        payload: written.ok ? { path: change.relPath } : { path: change.relPath, reason: written.reason ?? "denied" },
        provider: spec.owner
      });
    }
  };

  const reviewerReview: ReviewerReview = async (ctx: ReviewContext, gatesPassed: boolean): Promise<ReviewFindings> => {
    const adapter = createConfiguredAdapter(spec.reviewer, "real");
    const reviewerExecutionId = "integrated-reviewer";
    controls.register(() => adapter.cancel(reviewerExecutionId));
    const objective =
      `You are a cross-vendor reviewer. Review the code changes for correctness and completeness against the task: ` +
      `"${spec.objective}". The automated quality gates currently ${gatesPassed ? "PASS" : "FAIL"}. Read the changed files, ` +
      `then end your response with EXACTLY one line: "REVIEW_VERDICT: PASS" or "REVIEW_VERDICT: FAIL: <one-line reason>". ` +
      `Do not modify any files.`;
    const request = AgentExecutionRequestSchema.parse({
      executionId: reviewerExecutionId,
      provider: spec.reviewer,
      objective,
      cwd: ctx.worktreePath,
      readOnly: true,
      timeoutMs,
      ...(spec.reviewerModel ? { model: spec.reviewerModel } : {})
    });
    const texts: string[] = [];
    let wroteUnderReview = false;
    for await (const event of adapter.execute(request)) {
      if (event.type === "agent.message") {
        texts.push(String((event.payload as { text?: string }).text ?? ""));
      } else if (event.type === "file.changed") {
        wroteUnderReview = true;
      } else if (event.type === "quota.updated" || event.type === "usage.updated") {
        await sink({ type: event.type, payload: { ...(event.payload as Record<string, unknown>) }, provider: spec.reviewer });
      }
    }
    const full = texts.join("\n");
    const match = /REVIEW_VERDICT:\s*(PASS|FAIL)([^\n]*)/i.exec(full);
    const verdict = match ? (match[1].toUpperCase() === "PASS" ? "pass" : "fail") : "uncertain";
    await sink({ type: "agent.message", payload: { text: `cross-vendor verdict: ${verdict}` }, provider: spec.reviewer });

    const raw: RawReviewFinding[] = [];
    if (wroteUnderReview) {
      raw.push({ severity: "blocker", category: "unauthorized_write", evidence: `reviewer ${spec.reviewer} emitted file.changed under a read-only review`, impact: "the cross-vendor reviewer must be strictly read-only", requiredAction: "block and keep the reviewer read-only", confidence: 0.99 });
    }
    if (!gatesPassed) {
      raw.push({ severity: "major", category: "failing_gate", evidence: "the quality gates failed against the owner's changes", impact: "the task is not complete until the gates pass", requiredAction: "repair the implementation", confidence: 0.9 });
    }
    if (verdict === "fail") {
      raw.push({ severity: "major", category: "reviewer_defect", evidence: (match?.[2]?.replace(/^:\s*/, "").trim() || "the cross-vendor reviewer reported a defect").slice(0, 160), impact: "the cross-vendor reviewer flagged a real defect", requiredAction: "repair per the reviewer's finding", confidence: 0.8 });
    }
    const summary = raw.length === 0 ? `cross-vendor review by ${spec.reviewer}: PASS` : `cross-vendor review by ${spec.reviewer}: ${raw.length} finding(s)`;
    return buildReviewFindings(
      spec.reviewer,
      summary,
      raw.length > 0 ? raw : [{ severity: "observation", category: "clean_review", evidence: "cross-vendor reviewer found no defect and the gates pass", impact: "none observed", requiredAction: "proceed to the governed merge", confidence: 0.7 }]
    );
  };

  return { ownerImplement, reviewerReview };
}

/** Build the owner/reviewer plan for a run. `ownerSnapshot` is required for real mode. */
export function buildRunPlan(
  spec: IntegratedRunSpec,
  mode: ProviderMode,
  sink: StageSink,
  gitRunner: GitRunner,
  ownerSnapshot: CapabilitySnapshot | null,
  controls: RunControls
): RunPlan {
  if (mode === "real") {
    if (!ownerSnapshot) {
      throw new Error("real mode requires an observed owner capability snapshot");
    }
    return buildRealPlan(spec, sink, gitRunner, ownerSnapshot, controls);
  }
  return buildMockPlan(spec, sink, gitRunner);
}
